export const BEARS_ACTION_TYPES = {
    BEARS_GET_REQUEST: "BEARS: GET_REQUEST",
    BEARS_GET_REQUEST_SUCCESS: "BEARS: GET_REQUEST_SUCCESS",
    BEARS_GET_SINGLE_REQUEST:"BEARS:GET_SINGLE_REQUEST",
    BEARS_GET_SINGLE_REQUEST_SUCCESS:"BEARS:GET_SINGLE_REQUEST_SUCCESS",
    BEARS_RANDOM_REQUEST:'BEARS:RANDOM_REQUEST',
    BEARS_RANDOM_REQUEST_SUCCESS:'BEARS:RANDOM_REQUEST_SUCCESS',
    LOADING: "BEARS: LOADING",
    ERROR: "BEARS: ERROR"
}
